### ISSUE TITLE
Using the names argument with quantile

### ISSUE THREAD

**Issue by doug-friedman** [USGS-R/EflowStats#107]
I don't have a strong opinion on this, but I thought it was worth mentioning that you can achieve a decent speed increase by setting the names argument to false with the quantile function (https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html). Given the amount of times quantile is used, it could have a large effect on the efficiency of the code. However, this means that the results could only be referred to by numeric index which would reduce the clarity of the source code.

Here's a simple example that shows a 2x performance improvement just by removing the names.
```R
library(microbenchmark)

vec_100 = runif(100, 0, 10e3)

microbenchmark(
  names = quantile(vec_100, probs = seq(0.05,0.95,0.05), type=6),
  no_names = quantile(vec_100, probs = seq(0.05,0.95,0.05), type=6, names=F)
)
```

**Comment by tmills-usgs** [comment]
Interesting, is that common to other similar R functions?

I am going to leave it for now because I like the clarity, but lets leave this open in-case performance becomes an issue down the line

**Comment by doug-friedman** [comment]
Yeah it's super weird. I don't know of any other functions that have similar speedup due to having names.

**Comment by tmills-usgs** [comment]
how did you discover that then?

**Comment by doug-friedman** [comment]
It's in the documentation for the function under the names argument.

**Comment by tmills-usgs** [comment]
ha! ok, read the documentation, what a novel idea!

Thanks for you help on this Doug

**Comment by doug-friedman** [comment]
No problem! I probably spend too much time in the documentation.

**Comment by dblodgett-usgs** [comment]
Looking at the impact this change would have with a little project-wide code searching. 

We use quantile in 7 functions, 6 of the HIT functions. So, it has a very real potential of improving overall performance when calling hitAllStats. 

When quantile is called and called assigned to the variable `percentiles` (also: `percentiles_log10` and `hfcrit`), percentiles is referred to like: `percentiles["75%"]` 

I wonder if a good approach would be to assign the names we want to `percentiles`, `percentiles_log10`, and `hfcrit` to maintain the clarity and also get performance?

**Comment by doug-friedman** [comment]
I think that's a reasonable way of balancing code clarity and performance.

As an FYI, the performance improvement also scales with the number of quantiles called.
