### ISSUE TITLE
Notes due to non standard evaluation. 

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/EflowStats#115]
There are lots of notes in "check" like:
`ar1: no visible binding for global variable ‘month_val’`

These are due to what I think is called non-standard execution in dplyr? Not sure we HAVE to deal with these, but I hate notes!

**Comment by dblodgett-usgs** [comment]
Assigned this to me. It'll be a good chance to properly learn dplyr for once.

**Comment by doug-friedman** [comment]
FYI this stackoverflow answer does a good job of laying out the options - http://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when.

**Comment by dblodgett-usgs** [comment]
@tmills-usgs What do you say on this? I can change code such as: 
```
        flowSum_Mon <- dplyr::summarize(dplyr::group_by(x,month_val),
                                        meanFlow = mean(discharge))
```

to 
```
        flowSum_Mon <- dplyr::summarize_(dplyr::group_by_(x, "month_val"),
                                        meanFlow = ~mean(discharge))
```

and we have no note. You OK with this kind of change?
