### ISSUE TITLE
Function Naming 

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/EflowStats#134]
Before we cut a new release, let's put some thought into function naming. 

1. Consider combining the hit* functions a bit more. There is logic to having them broken out by type of stat AND by flow-characteristic (magnitude of high flows) being summarized, but there may be logic in combining into just type of stat (magnitude).
2. Reconsider naming of statistic calculation functions vs data utility functions. 

Generally, I like the idea that functions are named with the verb that characterizes what they do, but I'm not attached to it. We already do that with some functions: "dataCheck" "calcChangeEvents" etc. 

@wfarmer-usgs and @sarchfield do you have any good ideas to add here?

Current naming is:
<img width="702" alt="screen shot 2017-05-13 at 4 26 38 pm" src="https://cloud.githubusercontent.com/assets/1492803/26029375/15d002ee-37f9-11e7-90e3-01c59a6838fb.png">

**Comment by jread-usgs** [comment]
Can you clarify what the "hit" verb is supposed to mean to the user here? is that a domain thing?

**Comment by dblodgett-usgs** [comment]
hit came from the old function name hitStats and stands for Hydrologic Index Tool. HIT was the acronym name of the old C++ - based program that EflowStats is based on.

**Comment by dblodgett-usgs** [comment]
Following [tidyverse style](http://style.tidyverse.org/functions.html#naming) we could do:

- calc_ar1
- calc_base_flow_index
- calc_change_events
- calc_events
- calc_event_duration
- calc_flood_threshold
- calc_hydro_index_all
- calc_hydro_index_duration_high
- calc_hydro_index_*
- calc_magnificent_seven or calc_fundamental_daily_streamflow_stats 
_Note: (FDSS is used in the publication, Magnificent Seven is used in conversation)_
- calc_seasonality_metrics
- check_data
- get_EflowStats_sample_data
- get_wateryear
- get_wateryear_day

Using "hydro_index" would group all the functions that calculate what the [Hydrologic Index Tool](https://www.fort.usgs.gov/sites/default/files/products/publications/21598/21598.pdf) calculated.

**Comment by dblodgett-usgs** [comment]
We've discussed further lumping of the HIT statistics. It comes down to documentation. Since there are 171 individual statistics, it has seemed like a good idea to break them out into their basic groups.   Have a look at the documentation for [one of the functions](https://github.com/USGS-R/EflowStats/blob/master/R/hitDurationHigh.R)... if we lumped all these, we'd need to assemble all that information into some other format. Seems too long for normal function documentation. I'm game to do it, but I'm not sure what that other format would be. Is there an "extended R function documentation" pattern we could follow?

**Comment by dblodgett-usgs** [comment]
The check_data function is essentially only for input data. It makes sure that the data is clean and is ready (adheres to assumptions made) to be used in the rest of the package functions.

**Comment by jread-usgs** [comment]
So maybe `validate_inputs`?

**Comment by jread-usgs** [comment]
For the functions:
I think there are a number of templating and param sharing in roxygen
Also, when having so many functions, how easy is it for someone else to use the package and pass the main function a local env function to be used? Reminds me of glmtools pkg where we have main functions for derivatives, but you can also pass your own if it conforms to some basic structure

**Comment by dblodgett-usgs** [comment]
👍  to `validate` rather than `check`. @tmills-usgs what do you think?

I'm not sure how to come to conclusion regarding lumping of the individual HIT functions. Definitely better the way it is now from having WAY more in the previous version of the package. From a use case perspective, I only ever call hitAllStats and pass in the groups I want. I could totally see 
1. creating a vignette that includes all the statistic definitions (which are also in an old pdf report) and 
2. link to the list of all statistic definitions from one "calc_hydro_indices" function that lets you limit the groups of hydro indices the same way hitAllStats does now?

**Comment by tmills-usgs** [comment]
:+1: on `validate` rather than `check`

:+1: on 'calc_' naming convention for function groups, e.g. 'calc_frequencyHigh'

But I say leave the function grouping as-is. The documentation is not all that long with that convention and it makes it pretty easy to find documentation on the groups, see code for each statistic, and it would require a bit of work to get to the same point if we group.
