### ISSUE TITLE
Replace zoo's LOCF imputation with imputeTS' LOCF imputation

### ISSUE THREAD

**Issue by doug-friedman** [USGS-R/EflowStats#135]
I don't want to introduce more dependencies but there's a considerable performance improvement (and functional match) to using `na.locf` from imputeTS rather than zoo.

## **Performance Comparison**

Here's quick set of benchmark for LOCF (last observation carried forward) and NOCB (next observation carried backwards) using both zoo and imputeTS.

```R
library(microbenchmark)
# You will need zoo and imputeTS, but don't import them both 
# otherwise you'll get a ton of namespace conflicts

# Sample data
x = runif(1e3)

#...which we sabotage
x[sample(seq_along(x), 100)] = NA


# Test LOCF
z1 = zoo::na.locf(x)
z2 = imputeTS::na.locf(x, na.remaining="rm")

all.equal(z1,z2)


microbenchmark(
  z1 = zoo::na.locf(x),
  z1ish = zoo::na.locf0(x),
  z2 = imputeTS::na.locf(x, na.remaining="rm")
)


# Test NOCB 
z1 = zoo::na.locf(x, fromLast=T)
z2 = imputeTS::na.locf(x, option="nocb", na.remaining="rm")

all.equal(z1,z2)


microbenchmark(
  z1 = zoo::na.locf(x, fromLast=T),
  z1ish = zoo::na.locf0(x, fromLast=T),
  z2 = imputeTS::na.locf(x, option="nocb", na.remaining="rm")
)
```

## **Functional Match**
While there is a decent performance improvement to be had by substituting `zoo::na.locf` with `imputeTS::na.locf`, there is a much larger performance increase when you look at [the usage of `na.locf` in calcChangeEvents](https://github.com/USGS-R/EflowStats/blob/master/R/calcChangeEvents.R#L26). The `na.locf` function is used twice and the NAs leftover from the first run (forwards) are filled in with last run (backwards).

The `na.locf` function from imputeTS actually supports this process natively as part of the original function call. The result is much quicker when compared to the method currently implemented with zoo's `na.locf`.

```R
# Test LOCF then NOCB for remaining NAs
x_mini = c(NA, 1:5, NA, NA, 7, NA)

f1 = function(x){
  z1 = zoo::na.locf0(x)
  z1b = zoo::na.locf0(x, fromLast=T)
  z1[is.na(z1)] = z1b[is.na(z1)]
  z1
}

all.equal(f1(x), imputeTS::na.locf(x, na.remaining="rev"))

microbenchmark(
  f1(x),
  imputeTS::na.locf(x, na.remaining="rev")
)
```

## **Other Considerations**
It looks like the package relies on zoo for one other function and that's `na.approx`. There is a similar-ish implementation of this imputation method in imputeTS via `na.interpolation`, but it operates slightly differently and has less options than `na.approx`.

Here's a quick example using `x` and `x_mini`.

```R
# Test Approx
z1 = zoo::na.approx(x)
z2 = imputeTS::na.interpolation(x)

all.equal(z1,z2)


microbenchmark(
  z1 = zoo::na.approx(x),
  z2 = imputeTS::na.interpolation(x)
)


z1 = zoo::na.approx(x_mini)
z2 = imputeTS::na.interpolation(x_mini)

all.equal(z1,z2)

x_mini
z1 
z2 
```

`na.approx` drops leading and trailing NAs from the original vector during the process, but `na.interpolation` handles them with the existing functionality of `approx`. [Based on the usage of `na.approx` in magLow](https://github.com/USGS-R/EflowStats/blob/ca37de426129b31f8f934c34d43ed70170b4dcc6/R/magLow.R#L146), I think it shouldn't be an issue since the function already handles leading/trailing NAs.

**Comment by dblodgett-usgs** [comment]
I've been doing some benchmarking using the call we make in the hitAllStats test and I'm not seeing significant improvement. In the future, can you do your benchmarking on function calls that mimic the package usage? We really want to focus on things that are going to make a difference in the overall package and its real world performance. 

In general, switching to imputeTS will allow us to expand time-series filling functionality, so I think we'll go with it. I'll PR my branch with the performance changes. Hopefully you can take a look and make sure I'm doing what you expected @doug-friedman. Thanks!

**Comment by dblodgett-usgs** [comment]
Actually, can you just comment on the PR in my personal repo? https://github.com/dblodgett-usgs/EflowStats/pull/1/files

**Comment by doug-friedman** [comment]
No worries! I didn't mean to distract from the other updates.

Will do.

**Comment by dblodgett-usgs** [comment]
For the record, this does improve the calcChangeEvents performance a good bit. Very glad to have your input here!
