### ISSUE TITLE
ml17 and ml18 show discrepancies

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/EflowStats#136]
In #132, I found them to be different.

**Comment by dblodgett-usgs** [comment]
ML17 and ML18 Code:
```
// Recompute the mean annual flows

	for(i=0;i<nyrs;i++)
	{
		total = 0.;
		nmv = 0;
		for(j=0;j<366;j++)
		{
			if(q[i][j]!=999999.)
			{
				total = total + q[i][j];
				nmv++;
			}
		}
		meana[i] = total / nmv;
	}

// Compute the Baseflow Index 1

// Compute the minimum 7 day average flow for each year divided by the mean annual flow

	for(i=0;i<nyrs;i++)
	{
		minqm = 10000000.;
		for(j=0;j<360;j++)
		{
			total = 0.;
			nmv = 0;
			for(k=j;k<j+7;k++)
			{
				if(q[i][j]!=999999.)
				{
					total = total + q[i][j];
					nmv++;
				}
			}
			mdata[i] = total / nmv;
			if(mdata[i] < minqm) minqm = mdata[i];
		}
		mdata[i] = 0.;
		if(meana[i] != 0.) mdata[i] = minqm / meana[i];
	}
	stats(nyrs,mdata,&qmean,&qmedian,&qstdv);

// ML17		Base flow index 1.  Compute the mean annual flows.  Compute the minimum of a 7-day moving 
//			average flow for each year and divide them by the mean annual flow for that year.  ML17 is 
//			mean of those ratios.  (dimensionless)

	ML17 = qmean;

	LML17 = percentile(lb,nyrs,mdata);
	UML17 = percentile(ub,nyrs,mdata);

	hi[61] = ML17;	hil[61] = LML17;	hih[61] = UML17;

// ML18		Variability in base flow index 1.  Compute the standard deviation for the ratios of 
//			minimum 7-day moving average flows to mean annual flows for each year.  ML18 is the 
//			standard deviation times 100 divided by the mean of the ratios.  (%) 
//			Limits are not computed.

	ML18 = 999999;
	if(qmean != 0.) ML18 = (qstdv/qmean)*100.;
	hi[62] = ML18;
```

**Comment by dblodgett-usgs** [comment]
I don't read C++, but this appears to be holding to the definition. 

Base Flow Index is calculated here: https://github.com/USGS-R/EflowStats/blob/6440856b1c911e41fe09ea3548e95e70ee202f4d/R/bfi.R#L16
And Summarized by year here: https://github.com/USGS-R/EflowStats/blob/master/R/magLow.R#L99

@tmills-usgs or someone else can hopefully confirm that the new EflowStats is doing the rolling mean over the whole time series then summarizing by year where the C++ code is doing the rolling mean within each year without rolling over the break in year?

**Comment by tmills-usgs** [comment]
ml17 in this implementation of EflowStats (USGS-R/EflowStats) is actually doing the rolling mean BFI on an annual basis then taking the average of teh annual BFIs

[these lines](https://github.com/USGS-R/EflowStats/blob/master/R/hitMagLow.R#L99-L111)

**Comment by tmills-usgs** [comment]
The window size in [bfi.R](https://github.com/USGS-R/EflowStats/blob/master/R/bfi.R) appears to be set at 6 days?

**Comment by jiwalker-usgs** [comment]
`for(k=j;k<j+7;k++)` is the inner most loop that is supposed to get the 7 day total, but it looks like it isn't implemented correctly.  The `k` is not used in the calculation so the 7 day mean doesn't seem right.  I'm also pretty sure that the year loop should go to 359 so it doesn't exceed 366 when 7 is added.

**Comment by dblodgett-usgs** [comment]
So effectively, it's adding up the value of the first day of the week 7 times because it's using j and not incrementing j 7 times per week?

**Comment by jiwalker-usgs** [comment]
yeah, it just adds each day 7 times and then divides by 7

**Comment by jiwalker-usgs** [comment]
Also,
```
mdata[i] = 0.;
if(meana[i] != 0.) mdata[i] = minqm / meana[i];
```
the second statement is never run, I'm not sure how this ever worked.

**Comment by dblodgett-usgs** [comment]
meana[i] gets calculated up above. I think it would be non-zero so this would have run and set mdata[i] to non-zero if meana is non zero.

**Comment by jiwalker-usgs** [comment]
but it is set to 0 the line right before the if

**Comment by dblodgett-usgs** [comment]
No... that's `mdata` not `meana` super expressive variable names, eh?

**Comment by jiwalker-usgs** [comment]
ah, right you are

**Comment by dblodgett-usgs** [comment]
So, I think this means we're are OK. Will adjust the note over in #132
