### ISSUE TITLE
Add link to readme

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/EflowStats#147]
We'd like to categorize the packages in USGS-R. See the following link for more information:
https://owi.usgs.gov/R/packages.html

I'd recommend this package as "Research". When you decide what you think this package could be, you could add a badge to your readme:

[![status](https://img.shields.io/badge/USGS-Research-blue.svg)](https://owi.usgs.gov/R/packages.html#research)

If you wanted to include a link or note in your package startup message, we added that to some packages too. For example:

https://github.com/USGS-R/smwrQW/blob/master/R/smwrQW-package.R#L29

**Comment by dblodgett-usgs** [comment]
Closed in #149
