### ISSUE TITLE
findInterval needs vec that is sorted non-decreasingly

### ISSUE THREAD

**Issue by messamat** [USGS-R/EflowStats#155]
Hey there,
In calc_timingAverage.R (https://github.com/USGS-R/EflowStats/blob/23a680d8a4c657674828bc5d32f2d6a887f14fbb/R/calc_timingAverage.R):
```
       #...using findInterval
        break_pts = c(.1, seq(0.25, 2.25, by=.25)) * log_meanFlow
        x$interv = findInterval(x$log_discharge, break_pts)
        colwellMatrix = table(x$day, x$interv)
```
If discharge values are low and then log-transformed, all values will be negative and thus ordered decreasingly, throwing the following error:
```
Error in findInterval(x$log_discharge, break_pts) : 
  'vec' must be sorted non-decreasingly and not contain NAs"
```
Which stops the calc_allHIT computation.
It could be solved by simply adding:
`x$interv = findInterval(x$log_discharge, sort(break_pts))`

**Comment by dblodgett-usgs** [comment]
Thanks! I'll get this implemented soon. Do you have a little sample data that causes the issue we could work into a test?

**Comment by dblodgett-usgs** [comment]
@messamat -- see linked PR -- that's what you were after, right?

**Comment by tsangyp** [comment]
Hi, I still encountered the same error and found the suggested code was not updated yet.
x$interv = findInterval(x$log_discharge, sort(break_pts))

**Comment by dcallen** [comment]
Hi there ... I am getting the same error message in the calc_timingAverage function with some datafiles but not with others. I've attached a few test files that cause this error.  These all have discharge values < 1, so perhaps it is the same problem?
[test1.txt](https://github.com/USGS-R/EflowStats/files/2583072/test1.txt)
[test2.txt](https://github.com/USGS-R/EflowStats/files/2583073/test2.txt)
[test3.txt](https://github.com/USGS-R/EflowStats/files/2583074/test3.txt)





[test1.txt](https://github.com/USGS-R/EflowStats/files/2583060/test1.txt)
