### ISSUE TITLE
EflowStats not working with R version 3.5.1

### ISSUE THREAD

**Issue by teizeen** [USGS-R/EflowStats#162]
I am trying to install the EflowStats package, but I get the message that "package ‘EflowStats’ is not available (for R version 3.5.1)". Is there a plan to make this package work with this newest version of R?

**Comment by dblodgett-usgs** [comment]
Hi @teizeen -- sorry about that. I've just cut a new release of the package and put in to have it built on GRAN. https://github.com/USGS-R/grantools/pull/435 Not sure when the next gran build will be, but that should fix this for you. 

In the mean time, if you want the latest, you can do `devtools::install_github("USGS-R/EflowStats")`
