### ISSUE TITLE
Remove GRAN installation instructions

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/EflowStats#168]
Please remove the GRAN installation instructions as we work towards archiving the GRAN repository. Consider changing the `install_github` to use the "remotes" package (a much lighter weight package than devtools).

**Comment by dblodgett-usgs** [comment]
Fixed in c77910c88b2f4256e0713d99081fd09747e4e209

**Comment by ldecicco-USGS** [comment]
Dang your fast!

**Comment by dblodgett-usgs** [comment]
inbox zero is the only way to fly.
