### ISSUE TITLE
link to Henriksen et al. 2006 paper in readme broken?

### ISSUE THREAD

**Issue by chelseaclifford** [USGS-R/EflowStats#170]
The link to the Henriksen et al. 2006 paper under "References" in this package's readme file (i.e. http://www.fort.usgs.gov/products/publications/21598/21598.pdf) does not appear to lead to that paper at this time.  

(See https://github.com/USGS-R/EflowStats/blame/master/README.md#L45)
> Henriksen, J.A., Heasley, J. Kennen, J.G., and Nieswand, S., 2006, Users' manual for the Hydroecological Integrity Assessment Process software (including the New Jersey Assessment Tools): U.S. Geological Survey Open-File Report 2006-1093. 72 p. (http://www.fort.usgs.gov/products/publications/21598/21598.pdf)

Instead, it redirects me to apparently not very useful search results of USGS publications from Fort Collins (https://pubs.er.usgs.gov/search?contributingOffice=Fort+Collins+Science+Center).

As is, it is not obvious how to get to basic package documentation from this readme.  I am a beginner user of GitHub and may not be looking or reporting correctly.

**Comment by dblodgett-usgs** [comment]
Thanks for the report @chelseaclifford -- I've updated the link to: https://pubs.usgs.gov/of/2006/1093/report.pdf
