### ISSUE TITLE
EflowStats no longer available as package?

### ISSUE THREAD

**Issue by laurenmcphillips** [USGS-R/EflowStats#171]
I'm not sure if I'm missing something, but my student is having trouble installing the EflowStats package. It doesn't seem to exist anymore as a curated package installable via USGS-R?

**Comment by laurenmcphillips** [comment]
Got a helpful and quick reply from Laura DeCicco via Twitter so just updating here. EflowStats MUST be installed via USGS GitHub repository now, using 'remotes' package to access GitHub (see vignette)

To install the latest release of EflowStats see releases to find the latest version and use:

remotes::install_github("USGS-R/EflowStats@v5.0.1")
To install the latest and greatest build use the following code:

remotes::install_github("USGS-R/EflowStats")

**Comment by dblodgett-usgs** [comment]
Hi @laurenmcphillips -- are you seeing install instructions that indicate otherwise anywhere? The README here indicates the remotes options.
