### ISSUE TITLE
calc_allHIT is erroring out on the example code

### ISSUE THREAD

**Issue by malutz-usgs** [USGS-R/EflowStats#172]
I've been trying to familiarize myself with this package by running the code provided in the function examples.  When I try the example code for calc_allHIT:
x <- sampleData[c("date","discharge")]
calc_allHIT(x=x,yearType="water",stats="all",pref="mean",drainArea=50)

I get the following error:
Error: Problem with `summarise()` column `calc_bfi`.
i `calc_bfi = calc_bfi(discharge)`.
x function 'Rcpp_precious_preserve' not provided by package 'Rcpp'
i The error occurred in group 1: year_val = 2011.

Any ideas?

**Comment by dblodgett-usgs** [comment]
Hi @malutz-usgs -- Sorry to be a bit slow on the uptake here. Haven't looked at this package in a while. 

I'll have to do a little investigation. 

A little googling leads me to wonder if upgrading Rcpp would do the trick?

https://www.mail-archive.com/rcpp-devel@lists.r-forge.r-project.org/msg10226.html

**Comment by malutz-usgs** [comment]
Thanks, and sorry I didn't try that at the outset!  Updating the Rcpp package allowed the function to run/output results, but did result in the following warnings:
Warning messages:
1: na.interpolation will be replaced by na_interpolation.
           Functionality stays the same.
           The new function name better fits modern R code style guidelines.
           Please adjust your code accordingly. 
2: na.locf will be replaced by na_locf.
    Functionality stays the same.
    The new function name better fits modern R code style guidelines.
    Please adjust your code accordingly. 
3: na.locf will be replaced by na_locf.
    Functionality stays the same.
    The new function name better fits modern R code style guidelines.
    Please adjust your code accordingly. 

Thanks for your help!

**Comment by dblodgett-usgs** [comment]
Fixed this in #185
