### ISSUE TITLE
calc_frequencyHigh: years that do not have flood events can be removed for fh5 metric

### ISSUE THREAD

**Issue by jds485** [USGS-R/EflowStats#175]
Before the fh5 metric is computed, years with no events could be removed by the na.omit() function ([Line ref](https://github.com/USGS-R/EflowStats/blob/master/R/calc_frequencyHigh.R#L128)). It would be better to count these years as having no events, but I think that would make the fh1 and fh5 metrics identical. If this possibility of omitting years with no events is intentional, the code comments and/or reference manual should explain that difference in fh1 and fh5.

**Comment by dblodgett-usgs** [comment]
There was a good bit of ambiguity in the definitions of these metrics back when they were implemented. I would have to dig back into the reference document to see if there is supposed to be a difference. 

At the least, we should clarify what's going on in the documentation? Want to suggest a PR to fix?

**Comment by jds485** [comment]
Yes, I can handle the PR for this issue
