### ISSUE TITLE
find_changeEvents: errors out if a timeseries has no changes in flow

### ISSUE THREAD

**Issue by jds485** [USGS-R/EflowStats#177]
For sites that are ephemeral or perennially dry, there can be years without flow. If a timeseries has no changes in flow, this function will errors out on this [line](https://github.com/USGS-R/EflowStats/blob/79851fcbb22a076be19804f081ffdbb82d6acdfe/R/find_changeEvents.R#L22) because all entries are NA.

I think the function should return 0 changes in flow instead of erroring out.

**Comment by dblodgett-usgs** [comment]
Glad you are plowing through this package! Want to combine a fix with the PR to fix #175?

**Comment by jds485** [comment]
Yes, sounds good! For some context, a project I'm working on ran most of the EflowStats metrics on the GAGES2 dataset. Diagnosing the cause of NA, NaN, warnings, and errors from that run is how these edits are being found.

**Comment by dblodgett-usgs** [comment]
Right on. Hit me up on Teams if you need help.
