### ISSUE TITLE
calc_magLow: Handling zero flows for average of annual baseflow index values

### ISSUE THREAD

**Issue by jds485** [USGS-R/EflowStats#180]
Metric ml17 computes the average or median of annual baseflow index values. The annual values can be NaN when there are full years of 0 flow. ml17 and ml18 (std. dev. of ml17) could be computed with na.rm=TRUE to handle this case.

I can make a PR for this fix if you agree.

Line [ref](https://github.com/USGS-R/EflowStats/blob/main/R/calc_magLow.R#L103)

**Comment by dblodgett-usgs** [comment]
Yeah -- go for it.
