### ISSUE TITLE
Review function documentation.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/EflowStats#19]
Each function's documentation should be reviewed. During the first pass, glaring issues, such as out of date references or typos should be fixed. A list of deficiencies should be generated to be addressed in consultation with a statistical hydrologist. This task should be done both by a package maintainer (first) and an expert package user (second).

**Comment by tmills-usgs** [comment]
Some function documentation is not complete, or is done improperly. For example, FlowStatsAll argument data has description "data frame of daily flow data". This is totally ambiguous as to what this dataframe structure is, variables, etc.
