### ISSUE TITLE
FL3 Bug

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/EflowStats#20]
Report from user:  Doug Leasure <dleasure@email.uark.edu>
For FL3, you are using the aggregate function.  Unfortunately this drops all of the zeros for years with no low flow spells.  So, when you take the average you are measuring the average number of low flow spells in years that had low flow spells. This gives you a MUCH larger number than expected if you take the average number of low flow spells including years that had no low flow spells.

Initial reaction from jlthomps@usgs.gov: In the case of FL3, I will need to check on that. My test data may not have contained any years with no low flow spells, so that may have been missed.

**Comment by tmills-usgs** [comment]
This is correct. The FL3 is not calculating the proper median or mean. Working on it now.

Additionally, I have updated the sampleData to include a WY with no low flow spells
