### ISSUE TITLE
Error in col1_class != "Date" && col2_class != "numeric" :    'length = 3' in coercion to 'logical(1)'

### ISSUE THREAD

**Issue by annaybaynes** [USGS-R/EflowStats#200]
Hello,

I am a graduate student and I am trying to use the EflowStats package in R to run basic magnitude, timing, duration flow stats. I am keep running into this error:

calc_allHIT(x = cran, yearType = "water", stats = "all", pref = "mean", drainArea = 50)
Error in col1_class != "Date" && col2_class != "numeric" : 
  'length = 3' in coercion to 'logical(1)'

Would you be willing to give me some advice? I have date (date) and discharge (numeric) columns with no NAs and equal number of rows so I don't understand why I am still getting this error. Attached are two images

Thank you!
Anna
<img width="1440" alt="Screenshot 2024-02-02 at 4 25 57 PM" src="https://github.com/DOI-USGS/EflowStats/assets/158618069/da45c062-8ad2-40e8-b67b-816b6f7b382c">
<img width="1440" alt="Screenshot 2024-02-02 at 4 26 09 PM" src="https://github.com/DOI-USGS/EflowStats/assets/158618069/818cb4b4-280c-438d-9dd6-d371af66cd13">

**Comment by dblodgett-usgs** [comment]
Hi Anna -- sorry to be slow here. 

I'll need a reproducible example to be able to help debug. This guide may be helpful. https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html

**Comment by annaybaynes** [comment]
Hello Dr. Blodgett,

Thank you for your response! I found out it was because I have missing
data. I tried both removing the data and inserting NAs but the code would
not run. Is there a way to run this code with missing data? Attached is my
code and data sample.

Thank you!
Anna

On Tue, Feb 6, 2024 at 12:18 PM David Blodgett ***@***.***>
wrote:

> Hi Anna -- sorry to be slow here.
>
> I'll need a reproducible example to be able to help debug. This guide may
> be helpful.
> https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Freprex.tidyverse.org%2Farticles%2Freprex-dos-and-donts.html&data=05%7C02%7Cabaynes%40umass.edu%7Ca17465b93de047f9985808dc27379290%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638428366831262865%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=pdHFx28UQvTRvnCXPMUzkkuuEiunSU8Cn7ipB%2B7thyg%3D&reserved=0>
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDOI-USGS%2FEflowStats%2Fissues%2F200%23issuecomment-1930403283&data=05%7C02%7Cabaynes%40umass.edu%7Ca17465b93de047f9985808dc27379290%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638428366831262865%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=T36P8vc9KEitNGdVv21nZnh0q16yYrB7vdGlG8Wdq%2B4%3D&reserved=0>,
> or unsubscribe
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBF2FDVLR4JZIXL45Q2LF5QLYSJQUTAVCNFSM6AAAAABCXIE3UOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZQGQYDGMRYGM&data=05%7C02%7Cabaynes%40umass.edu%7Ca17465b93de047f9985808dc27379290%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638428366831262865%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=BYYvnhM3Z%2F2EFGTiFP1SY6OovtiNDnn1dKuZTG82gyU%3D&reserved=0>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
*Anna Baynes*


*Graduate Research AssistantOrganismic and Evolutionary BiologyUniversity
of Massachusetts *
e: ***@***.***
c: 919-475-8562
Pronouns: (she/her)

**Comment by dblodgett-usgs** [comment]
Hi Anna, unfortunately, no. The statistics in eflowstats assume complete data.

**Comment by annaybaynes** [comment]
Hi Dr. Blodgett,

Thanks for letting me know. Do all functions in EflowStats require complete
data?

Thank you!
Anna

On Thu, Feb 22, 2024 at 10:33 PM David Blodgett ***@***.***>
wrote:

> Hi Anna, unfortunately, no. The statistics in eflowstats assume complete
> data.
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDOI-USGS%2FEflowStats%2Fissues%2F200%23issuecomment-1960687287&data=05%7C02%7Cabaynes%40umass.edu%7C086167424a594a76605a08dc342021e8%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638442559835215183%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=AACJ70aMWvLaYbjiPE7Rv8mh9jGXVRT3ot6oymp5TmE%3D&reserved=0>,
> or unsubscribe
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBF2FDVI7X7USXKHYUDJ3IQDYVAEWVAVCNFSM6AAAAABCXIE3UOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRQGY4DOMRYG4&data=05%7C02%7Cabaynes%40umass.edu%7C086167424a594a76605a08dc342021e8%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638442559835215183%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=xvGwjonkO3AfqQ9R1pB8U80MCNUDSn3lJi2CfJwtpCo%3D&reserved=0>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
*Anna Baynes*


*Graduate Research AssistantOrganismic and Evolutionary BiologyUniversity
of Massachusetts *
e: ***@***.***
c: 919-475-8562
Pronouns: (she/her)

**Comment by dblodgett-usgs** [comment]
I believe so, but you would have to check the specific documentation of the functions.
