### ISSUE TITLE
Clarify and possibly add constraints for POR of diffstats

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/EflowStats#25]
For the Diff Stats, it is my understanding that it is taking the difference between statsout1 and statsout2. 

In my output files, my statsout1 shows a POR specific to each gage. My statsout2 shows the POR I have
for my simulations, i.e. each is 2001-2011. 
So, does this mean that in the DiffStats it is taking a difference based on stats calculated on a different POR?

response: yes, that is what it means. I considered that issue, but hadn't yet done anything about it because I wasn't sure if we would want a blanket limit to the same period or not, or if that limit should come earlier, so that stats are calculated on the same POR for each, using the least available POR?

**Comment by tmills-usgs** [comment]
Need input from qualified user

**Comment by dblodgett-usgs** [comment]
Would Will Farmer be able to help with this one?

**Comment by tmills-usgs** [comment]
@wfarmer-usgs
