### ISSUE TITLE
Clean Up ObservedFlowStatsMulti

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/EflowStats#27]
Noticing some things that could be improved. 
Specifically here: https://github.com/USGS-R/EflowStats/blob/master/R/ObservedStatsOtherMulti.R#L42 I don't think this is doing what it should.
And here: https://github.com/USGS-R/EflowStats/blob/master/R/ObservedStatsOtherMulti.R#L120 this should be a string match!

Would be worth sweeping the package for other places where sites are being treated as numerical types, this is totally subject to breaking because of the leading 0 issue.

**Comment by tmills-usgs** [comment]
Correct me if I am wrong, but from the code it looks like the drainage area filename must contain the character string "drain".

 https://github.com/USGS-R/EflowStats/blob/master/R/ObservedStatsOtherMulti.R#L36

If so, it should be indicated in the function documentation.

[This](https://github.com/USGS-R/EflowStats/blob/master/R/ObservedStatsOtherMulti.R#L42) appears to be doing what its supposed to.

**Comment by tmills-usgs** [comment]
Fixed [string match](https://github.com/USGS-R/EflowStats/blob/master/R/ObservedStatsOtherMulti.R#L120). Also added documentation indicating filename specifics.
