### ISSUE TITLE
CompareStats

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/EflowStats#48]
Compare stats returns a list of dataframes that are not named. These dataframes need to be named appropriately and documented

**Comment by tmills-usgs** [comment]
They are now named, but documentation is still needed

**Comment by tmills-usgs** [comment]
I have not been able to decipher, for certain, what this function is supposed to be doing with respect to simulated/observed. It seems that either it can a) compute statistics for a simulated and observed discharge dataset, compare the results, and supply GOF stats for the results or b) do the same thing but for datasets from two different time periods.

This can be run on user supplied data "datapath1 and datapath2" or data from USGS stations "startDt and startDt2".

This desperately needs to be clarrified in the function documentation. Once this is done, the function can be re-tooled to be more user friendly and perform faster.

@dblodgett-usgs Can you chime in here?

**Comment by dblodgett-usgs** [comment]
I think you are spot on with your interpretation. The way you call it IS horrible. I remember working with this and being ultra confused. Not sure I have the mental space to think about a good solution, but the simpler the better in my opinion. To the point of breaking it into two functions if that makes it simpler.

**Comment by tmills-usgs** [comment]
This function is used by the web app isn't it?

**Comment by dblodgett-usgs** [comment]
The scripts that are currently checked into the web processing service are here: https://github.com/USGS-CIDA/WaterSMART/tree/master/watersmart-wps/src/main/webapp/R/r_scripts

The stats_compare_icp is no longer in use. 

stats_huc12 and stats_nwis are in use. Looks like they use: calculateStatsGroups
