### ISSUE TITLE
ml14.16 for small streams

### ISSUE THREAD

**Issue by lemerio** [USGS-R/EflowStats#65]
Hi!

If you have data where the median (or mean) annual discharge is zero (e.g. in my small catchment data from Scandinavia) in any of the input year the resulted index value will be NaN or NA depending of the case. 

This could be avoided by replacing zeros in columns $medbyyr and $meanbyyr with very low value, e.g:
computeml14[, 3:4][which(computeml14[, 3:4] == 0, arr.ind = TRUE)] <- 0.00001

Or just ingore NaN / NA values by adding na.rm = TRUE (I think this would be worse because it totally ignores part of the data):

ml14 <- round(mean(dfml14, na.rm = TRUE), digits = 2)
ml16 <- round(median(dfml14, na.rm = TRUE), digits = 2)
ml15 <- round(mean(dfml15, na.rm = TRUE), digits = 2)

-Leo

Ps. Thanks for the great work you have done in EflowStats!

**Comment by tmills-usgs** [comment]
Hi Leo,

Thank you for the issue posts. I am in the process of rewriting much of the EflowStats package to improve the performance and make the package more generalized for data outside of the USGS. Also, the package will be a little more intuitive and better documented. 

I will have a warning to the user in the new package functions alerting them to the presence of missing values in their data. The package by default will then ignore the missing values, but the warning message will let the user know that they should handle the missing values before running the statistics. As you suggested, a substitution of a low value or a linear interpolation between measured values would be more appropriate.

If you'd like, I can alert you when the new package has an early development version ready for release.

**Comment by lemerio** [comment]
Hi!

Thanks for the reply! Good to hear that you are developing {EflowStats} further! Definitely I would like to know when there is a new early development package. 

If you have plans to have more indicators included, one could be Julian day for 7-day low/high flow period in addition to timing of the 1-day extremes.
