### ISSUE TITLE
Bugs in many fh* functions

### ISSUE THREAD

**Issue by jasonelaw** [USGS-R/EflowStats#69]
Many (but not all of the fh*) functions rely on the data being sorted in chronological order. However, none of these functions test this sort order. In fact, the default dataset ```sampleData``` used in the examples is not in chronological order:
```
> library(EflowStats)
> fh9(sampleData)
[1] 9.5
> sampleData <- sampleData[order(sampleData$date),]
> fh9(sampleData)
[1] 7.5
```
Most of the fh* functions seem to be affected by this bug and so the calculations are almost invariably wrong (including the examples used in the help) using data that is not correctly sorted. These functions should not be used directly without sorting.

**Comment by tmills-usgs** [comment]
Thanks for pointing that out, In the new functions the input data frame is checked for required classes, variables, na values, etc and then sorted. I will make sure this is implemented in the fh group of functions as well

**Comment by tmills-usgs** [comment]
Checkout this for an example of how I am handling this.

[durationHigh](EflowStats/R/durationHigh.R)

note that all loops have been removed.Calculations for stats are now generally 10x faster

**Comment by tmills-usgs** [comment]
OK, found this issue as well. Fixed in new package
