### ISSUE TITLE
failed to install dependent packages

### ISSUE THREAD

**Issue by tsangyp** [USGS-R/EflowStats#7]
When installing EflowStats in R,
install.packages("EflowStats",repos="http://usgs-r.github.com",type="source")

It shows error message as below:
ERROR: dependencies 'chron', 'doBy', 'hydroGOF', 'lmomco' are not available for package 'EflowStats'

Please assist this problem. Thanks so much!

**Comment by deddy23** [comment]
Have there been any issues when installing with 'R' v.3.0? I am still new to 'R' but this an exceptional package for my own research. 
thank you!

**Comment by deddy23** [comment]
Have there been any known errors with stats outputs? I keep receiving negative discharge values and am wondering if EflowStats is somehow incorporating 'false' data.
This is a phenomenal package, thank you!

**Comment by jlthomps** [comment]
No, there isn't any extra data being filled in or added. Do you mean you are getting negative values for means or medians? Or annual maximums, minimums, etc? Have you looked at the range of discharge values in your source data? Some datasets use placeholders, such as -9999, for flagged data. Please feel free to contact me with more specifics if you can't determine where the negatives are coming in.

**Comment by deddy23** [comment]
Thank you for the reply! Yeah the placeholders are being used during the calculations. Is anyone aware of an option to input exact dates (i.e.- 2014-01-01) instead of just year? @jlthomps 
R as a language is new to me, yet this has been extremely user friendly and sincerely appreciate any help, Thanks!

**Comment by dblodgett-usgs** [comment]
@deddy23, I'm going through old tickets and just noticed this one is outstanding. Since the original issue from this ticket was taken care of, I'm going to close it. If you'd like to open a new ticket to suggest the ability to specify exact dates, please do.
