### ISSUE TITLE
https changeover

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/EflowStats#73]
Found these lines with http .gov URLs using https://github.com/wdwatkins/gran_http_gov

HTTPS is supposed be available for everything by the end of December, but may not be yet.

Some of these in .md and other documentation files won't show up on github unless you go to raw file. Line numbers reference the number in the raw file when opened in a text editor, so the link may not point you to the right spot in some cases if lines are wrapping, etc.

- [ ] https://github.com/USGS-R/EflowStats/blob/master/DESCRIPTION#L20
- [ ] https://github.com/USGS-R/EflowStats/blob/master/DESCRIPTION#L35
- [ ] https://github.com/USGS-R/EflowStats/blob/master/LICENSE.note#L2
- [ ] https://github.com/USGS-R/EflowStats/blob/master/R/get_obsdata.R#L10
- [ ] https://github.com/USGS-R/EflowStats/blob/master/R/getXMLWML1.1Data.R#L12
- [ ] https://github.com/USGS-R/EflowStats/blob/master/README.md#L14
- [ ] https://github.com/USGS-R/EflowStats/blob/master/README.md#L25
- [ ] https://github.com/USGS-R/EflowStats/blob/master/README.md#L31
- [ ] https://github.com/USGS-R/EflowStats/blob/master/inst/doc/EflowStats.R#L133
- [ ] https://github.com/USGS-R/EflowStats/blob/master/inst/doc/EflowStats.Rnw#L173
- [ ] https://github.com/USGS-R/EflowStats/blob/master/inst/doc/EflowStats.Rnw#L718
- [ ] https://github.com/USGS-R/EflowStats/blob/master/inst/doc/EflowStats.Rnw#L740
- [ ] https://github.com/USGS-R/EflowStats/blob/master/inst/doc/EflowStats.Rnw#L760
- [ ] https://github.com/USGS-R/EflowStats/blob/master/man/get_obsdata.Rd#L20
- [ ] https://github.com/USGS-R/EflowStats/blob/master/man/getXMLWML1.1Data.Rd#L21
- [ ] https://github.com/USGS-R/EflowStats/blob/master/tests/testthat/webRetrievalTests.R#L11
- [ ] https://github.com/USGS-R/EflowStats/blob/master/vignettes/EflowStats.Rnw#L173
- [ ] https://github.com/USGS-R/EflowStats/blob/master/vignettes/EflowStats.Rnw#L718
- [ ] https://github.com/USGS-R/EflowStats/blob/master/vignettes/EflowStats.Rnw#L740
- [ ] https://github.com/USGS-R/EflowStats/blob/master/vignettes/EflowStats.Rnw#L760

**Comment by dblodgett-usgs** [comment]
This issue is covered by the new package. Closing.
