### ISSUE TITLE
Call to previous contributors

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/EflowStats#97]
@doug-friedman , @jasonelaw ,@sarchfield , @lemerio ,  @dblodgett-usgs , @wfarmer-usgs

Hello everyone, I am tagging you here to notify you that I have a first cut at a re-implementation of EflowStats. This new package address a number of the performance and user-experience issues with the original package. Additionally, a number of theoretical issues with the statistics themselves have been discovered and an attempt was made to address these.

If any of you are still interested, I would appreciate any feedback and/or code review. I have tabulated all known issues with the original statistics on the readme github page.

Please see the vignette in the package for an example workflow if you want to try out the new package.

Thanks and I look forward to your feedback,
Joe Mills

**Comment by jasonelaw** [comment]
I looked at things briefly and it looks much simpler. I'll try to make some time to look more carefully and let you know if I see anything.

**Comment by doug-friedman** [comment]
I scanned the new code and everything looks way simpler/cleaner now. I made a few pull requests to optimize and standardize a few of the smaller functions where I could.

Three quick pieces of general feedback.

1. Is there a reason you're not using the pipe (%>%) operator? It might make some of the multi-step dplyr code more clear.
2. I would recommend adding a few quick error checks to the functions not including a dataCheck call (e.g. waterYear). The presence of NAs/nulls or improper date formats could error these out.
3. I would also recommend consistency in the removal of NAs/nulls for functions that could possibly be passed them. There are some functions that remove them (e.g. cv) and others that don't (e.g. bfi).

**Comment by tmills-usgs** [comment]
Hi Doug, 

Thank you for the comments, I will work on getting those addressed.

Regarding the use of pipes, I don't really like using pipes in packages because it makes debugging difficult and can also cause some issues with performance if that function is then applied in a loop.

Pipes are great for making your analysis code more concise, but there is not really any advantage to them in a package/function. That is my two cents

**Comment by doug-friedman** [comment]
No problem! I agree about debugging pipelines so no worries there.

**Comment by dblodgett-usgs** [comment]
PR #120 has a lit of differences found between some old output from the windows application and the new code. 

Of note,
dl14 and dl15 are more than 10% different. 
ra3, ra4, and ra7, are more than 100% different.

**Comment by dblodgett-usgs** [comment]
There must be something wrong with the fall values in the old calculations. ra3, 4, and 7 all use https://github.com/USGS-R/EflowStats/blob/master/R/rateChange.R#L50

Debugging in there, it looks correct according to the documentation.

**Comment by dblodgett-usgs** [comment]
Going to close this. Will reach out to individuals for further review in preparation for a data release and CRAN submission.
