### ISSUE TITLE
Rename hit functions.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/EflowStats#98]
hitStats becomes hitAllStats and all the sub functions become hit* so they group nicely in the package index.

**Comment by tmills-usgs** [comment]
Are we still doing this or is it going to hammer all your work in testing?

**Comment by tmills-usgs** [comment]
could do a find-in-files and replace

**Comment by dblodgett-usgs** [comment]
I think we should do it sometime soon. I'd be happy to do the refactor.
